# Generated by Django 3.1.4 on 2020-12-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAPI', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='FirstAPI.Tag'),
        ),
    ]
